version: '3'

services:
  test_service:
    image: test:latest
    command: npm run test
    environment:
      - REDIS_HOST=redis
      - FAIL=true
    depends_on:
      - redis
  redis:
    image: redis:3.2-alpine
