image:
  repository: 676206137628.dkr.ecr.eu-west-1.amazonaws.com/codefresh
  tag: master
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 512Mi
    cpu: 300m
service:
  type: ClusterIP
  port: 80