apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "node-js.fullname" . }}
  labels:
    app: {{ template "node-js.name" . }}
    chart: {{ template "node-js.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "node-js.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "node-js.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: >-
            codefresh-generated-676206137628.dkr.ecr.eu-west-1.amazonaws.com-codefresh-default
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 180
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}