image:
  repository: 676206137628.dkr.ecr.eu-west-1.amazonaws.com/codefresh
  tag: master
  pullPolicy: Always
  pullSecret: codefresh-generated-676206137628.dkr.ecr.eu-west-1.amazonaws.com-codefresh-default
resources:
  requests:
    memory: 512Mi
    cpu: 300m
service:
  type: LoadBalancer
  port: 80
healthcheck:
  path: /healthcheck
env:
  secrets:
    REDIS_PASSWORD:
      name: redis
      key: redis-password
  vars:
    APP_VERSION: 1
    REDIS_HOST: redis